apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-guru
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-guru
  template:
    metadata:
      labels:
        app: book-guru
    spec:
      containers:
        - name: book-guru
          image: book-guru:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"