apiVersion: v1
kind: Service
metadata:
  name: book-guru-service
  namespace: default
  labels:
    app: book-guru
spec:
  type: NodePort
  selector:
    app: book-guru
  sessionAffinity: None
  ports:
    - name: http
      protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30050