apiVersion: v1
kind: Service
metadata:
  name: book-guru-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: book-guru
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30050